### ISSUE TITLE
Error in Part 1.

### ISSUE THREAD

**Issue by mike-lawrence** [Cascadia-R/gRadual-intRoduction-tidyverse#2]
Line 119 in Part 1 should be "gdpPercap" not "gpdPerCap"

**Comment by laderast** [comment]
Hi Mike,

Good eye.

I believe that is an intentional mistake by Chester to avoid mindless copy/paste. @ismayc ?

**Comment by ismayc** [comment]
Yep.  That is a typo.  I would say it was intentional but that would be lying.  I will fix it as soon as I can.  Thanks, @mike-lawrence!
